# Generated by Django 5.1.15 on 2026-06-18 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Ключ сессии (гость)')),
                ('input_data', models.JSONField(default=dict, verbose_name='Исходные данные')),
                ('results', models.JSONField(default=list, verbose_name='Результаты оценки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('normative_doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='standards.normativedocument', verbose_name='Нормативный документ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка качества',
                'verbose_name_plural': 'Оценки качества',
                'ordering': ['-created_at'],
            },
        ),
    ]
