# Generated by Django 5.2.16 on 2026-07-13 20:51

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('section_label', models.CharField(blank=True, max_length=50, verbose_name='Пункт/раздел')),
                ('text', models.TextField(verbose_name='Текст фрагмента')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('embedding_model_version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фрагмент документа',
                'verbose_name_plural': 'Фрагменты документов',
                'ordering': ['source', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('doc_type', models.CharField(help_text='gost / np / sto / other', max_length=20, verbose_name='Тип')),
                ('doc_number', models.CharField(blank=True, max_length=100, verbose_name='Номер документа')),
                ('source_url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('storage_key', models.CharField(blank=True, max_length=255, verbose_name='Ключ в хранилище')),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Источник документа',
                'verbose_name_plural': 'Источники документов',
                'ordering': ['doc_number'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('llm_provider', models.CharField(blank=True, max_length=30)),
                ('llm_model', models.CharField(blank=True, max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Консультант')], max_length=10)),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_consultant.consultantsession')),
                ('cited_chunks', models.ManyToManyField(blank=True, related_name='cited_in', to='ai_consultant.documentchunk')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_consultant.documentsource'),
        ),
    ]
