# Generated by Hermes Agent
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_consultant', '0004_golden_anchor'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantsession',
            name='wizard_state',
            field=models.JSONField(null=True, blank=True, verbose_name='Состояние мастера расчёта'),
        ),
    ]