# Generated by Django 5.1.15 on 2026-06-18 21:47

import apps.cards.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название техкарты')),
                ('input_data', models.JSONField(default=dict, verbose_name='Исходные данные')),
                ('generated_data', models.JSONField(default=dict, verbose_name='Вычисленные данные')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to=apps.cards.models.tech_card_docx_path, verbose_name='Файл DOCX')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=apps.cards.models.tech_card_pdf_path, verbose_name='Файл PDF')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('generated', 'Сгенерирована'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатная разработка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('normative_doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='standards.normativedocument', verbose_name='Нормативный документ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_cards', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Технологическая карта',
                'verbose_name_plural': 'Технологические карты',
                'ordering': ['-created_at'],
            },
        ),
    ]
