# Generated by Django 5.1.15 on 2026-06-18 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NDTMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('VT', 'Визуальный и измерительный (ВИК)'), ('RT', 'Радиографический (РК)'), ('PT', 'Капиллярный (ПВК)'), ('LT', 'Контроль герметичности (КГ)'), ('UT', 'Ультразвуковой (УЗК)'), ('MT', 'Магнитопорошковый (МПД)')], max_length=5, unique=True, verbose_name='Обозначение метода')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование метода')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Метод НК',
                'verbose_name_plural': 'Методы НК',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='NormativeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Например: ГОСТ 7512, ГОСТ Р 50.05.7-2019', max_length=100, unique=True, verbose_name='Обозначение документа')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, max_length=150, verbose_name='Краткое наименование')),
                ('data_module', models.CharField(blank=True, help_text='Путь к Python-модулю с данными, например: ndt_data.gost_7512', max_length=200, verbose_name='Модуль данных')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='Версия / год')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('has_card_template', models.BooleanField(default=False, verbose_name='Есть шаблон техкарты')),
                ('has_quality_criteria', models.BooleanField(default=False, verbose_name='Есть критерии оценки качества')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='standards.ndtmethod', verbose_name='Метод НК')),
            ],
            options={
                'verbose_name': 'Нормативный документ',
                'verbose_name_plural': 'Нормативные документы',
                'ordering': ['method', 'code'],
            },
        ),
    ]
