# Generated by Django 5.2.15 on 2026-06-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forum_blocked',
            field=models.BooleanField(default=False, help_text='Пользователь не может писать сообщения в форуме', verbose_name='Заблокирован в форуме'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='forum_blocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата блокировки в форуме'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='forum_blocked_reason',
            field=models.TextField(blank=True, verbose_name='Причина блокировки в форуме'),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='techcard_credits',
            field=models.IntegerField(default=0, verbose_name='Оплаченных кредитов (остаток)'),
        ),
    ]
