# Generated by Django 4.2.13 on 2026-06-19 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormativeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Например: ГОСТ Р 50.05.07-2018', max_length=100, unique=True, verbose_name='Обозначение документа')),
                ('full_name', models.TextField(verbose_name='Полное наименование')),
                ('control_method', models.CharField(choices=[('RT', 'Радиографический контроль (РГК)'), ('VT', 'Визуальный и измерительный контроль (ВИК)'), ('PT', 'Капиллярный контроль (КК)'), ('LT', 'Контроль герметичности (КГ)'), ('UT', 'Ультразвуковой контроль (УЗК)'), ('MT', 'Магнитопорошковый контроль (МПД)')], max_length=5, verbose_name='Метод контроля')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_implemented', models.BooleanField(default=False, help_text='Если снято — показывается пометка «В разработке»', verbose_name='Реализован (не заглушка)')),
                ('sort_order', models.IntegerField(default=100, verbose_name='Порядок сортировки')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Нормативный документ',
                'verbose_name_plural': 'Нормативные документы',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TechCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Наименование объекта')),
                ('card_number', models.CharField(blank=True, max_length=50, verbose_name='Номер техкарты')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('done', 'Готова'), ('error', 'Ошибка генерации')], default='draft', max_length=20, verbose_name='Статус')),
                ('input_data', models.JSONField(default=dict, verbose_name='Исходные данные')),
                ('generated_data', models.JSONField(default=dict, verbose_name='Параметры техкарты')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='techcards/docx/%Y/%m/', verbose_name='Файл DOCX')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='techcards/pdf/%Y/%m/', verbose_name='Файл PDF')),
                ('was_free', models.BooleanField(default=False, verbose_name='Создана бесплатно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('normative_doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='techcards.normativedocument', verbose_name='Нормативный документ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techcards', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Технологическая карта',
                'verbose_name_plural': 'Технологические карты',
                'ordering': ['-created_at'],
            },
        ),
    ]
