# Generated by Django 5.2.15 on 2026-06-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normativedocument',
            options={'ordering': ['sort_order', 'code'], 'verbose_name': 'Документ НДТ', 'verbose_name_plural': 'Документы НДТ'},
        ),
        migrations.AddField(
            model_name='normativedocument',
            name='document_kind',
            field=models.CharField(choices=[('normative', 'Нормативный документ'), ('methodological', 'Методический документ')], default='normative', help_text='Нормативный или методический документ', max_length=20, verbose_name='Вид документа'),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('techcards', 'NormativeDocument').objects.filter(
                code='ГОСТ Р 50.05.07-2018',
            ).update(document_kind='methodological'),
            migrations.RunPython.noop,
        ),
    ]
