# Generated by Django 4.2.13 on 2026-06-19 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards_count', models.IntegerField(verbose_name='Количество операций')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена, руб.')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
                'ordering': ['cards_count'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма, руб.')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('succeeded', 'Оплачено'), ('canceled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('yookassa_payment_id', models.CharField(blank=True, max_length=200, verbose_name='ID платежа ЮKassa')),
                ('yookassa_confirmation_url', models.URLField(blank=True, max_length=500, verbose_name='URL подтверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.tariffplan', verbose_name='Тарифный план')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
