# Generated by Django 5.2.16 on 2026-07-13 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscription_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_ai_consultant',
            field=models.BooleanField(default=False, help_text='Доступ к модулю ИИ-консультанта по нормативной базе', verbose_name='Включает ИИ-консультанта'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.subscriptionplan', verbose_name='План подписки'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='generation_limit',
            field=models.PositiveIntegerField(help_text='Сколько техкарт можно создать за срок подписки', verbose_name='Лимит генераций за период'),
        ),
    ]
