# Generated by Django 4.2.13 on 2026-06-19 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Ключ сессии (гость)')),
                ('normative_doc', models.CharField(default='НП-105-18', max_length=100, verbose_name='Нормативный документ')),
                ('weld_category', models.CharField(max_length=10, verbose_name='Категория сварного соединения')),
                ('wall_thickness', models.FloatField(verbose_name='Толщина стенки, мм')),
                ('weld_length', models.FloatField(blank=True, null=True, verbose_name='Длина шва, мм')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('verdict', models.CharField(blank=True, help_text='ГОДЕН или БРАК', max_length=10, verbose_name='Заключение')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка качества',
                'verbose_name_plural': 'Оценки качества',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefectEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(choices=[('crack', 'Трещина'), ('lack_of_fusion', 'Несплавление'), ('incomplete_penetration', 'Непровар'), ('pore', 'Пора'), ('slag', 'Шлаковое включение'), ('tungsten', 'Вольфрамовое включение'), ('undercut', 'Подрез'), ('excess_penetration', 'Превышение проплава'), ('surface_defect', 'Поверхностный дефект')], max_length=50, verbose_name='Тип дефекта')),
                ('size_1', models.FloatField(default=0, verbose_name='Размер 1 (диаметр/глубина), мм')),
                ('size_2', models.FloatField(default=0, verbose_name='Размер 2 (длина/ширина), мм')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='quality.qualityassessment', verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Дефект',
                'verbose_name_plural': 'Дефекты',
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_acceptable', models.BooleanField(verbose_name='Допустимо')),
                ('criterion', models.CharField(max_length=500, verbose_name='Критерий приёмки')),
                ('reason', models.TextField(verbose_name='Обоснование')),
                ('reference', models.CharField(max_length=200, verbose_name='Ссылка на пункт НД')),
                ('max_allowed_mm', models.FloatField(default=0, verbose_name='Максимально допустимый размер, мм')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quality.qualityassessment')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quality.defectentry')),
            ],
            options={
                'verbose_name': 'Результат оценки',
                'verbose_name_plural': 'Результаты оценки',
            },
        ),
    ]
