# Generated by Django 5.2.15 on 2026-06-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityassessment',
            name='inclusion_cluster_count_100mm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Число включений и скоплений на 100,0 мм'),
        ),
        migrations.AddField(
            model_name='qualityassessment',
            name='large_inclusion_count_100mm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Число крупных включений на 100,0 мм'),
        ),
    ]
